"""Ajout colonne contrat dans Client

Revision ID: 059f15535207
Revises: 886f06583864
Create Date: 2025-04-24 11:51:37.794076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059f15535207'
down_revision = '886f06583864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrat', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('contrat')

    # ### end Alembic commands ###
