"""Ajout du champ temps_facturé

Revision ID: 1e499d11baef
Revises: a7c040ddbb35
Create Date: 2025-04-24 09:52:33.029014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e499d11baef'
down_revision = 'a7c040ddbb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temps_facture_personnalise', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('temps_facture_personnalise')

    # ### end Alembic commands ###
