"""Passage à debut_fin

Revision ID: 3b1bf0566a0f
Revises: e5a0c5ac987b
Create Date: 2025-04-25 09:19:55.501443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1bf0566a0f'
down_revision = 'e5a0c5ac987b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temps_passe_personnalise', sa.Integer(), nullable=True))
        batch_op.drop_column('temps_passe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temps_passe', sa.INTEGER(), nullable=True))
        batch_op.drop_column('temps_passe_personnalise')

    # ### end Alembic commands ###
