"""Ajout colonne soldes_annee

Revision ID: 6083b378f777
Revises: ef2ab8a6cd87
Create Date: 2025-04-24 15:29:46.956917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6083b378f777'
down_revision = 'ef2ab8a6cd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde_minutes', sa.Integer(), nullable=True))
        batch_op.drop_column('solde_annuel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde_annuel', sqlite.JSON(), nullable=True))
        batch_op.drop_column('solde_minutes')

    # ### end Alembic commands ###
