"""Ajout du champ rapport

Revision ID: 856ba7b24132
Revises: 
Create Date: 2025-04-23 11:43:39.700009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856ba7b24132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rapport', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('rapport')

    # ### end Alembic commands ###
