"""Ajout du champ solde

Revision ID: 886f06583864
Revises: 1e499d11baef
Create Date: 2025-04-24 10:02:26.116862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886f06583864'
down_revision = '1e499d11baef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('solde_minutes')

    # ### end Alembic commands ###
