"""Passage à debut_fin

Revision ID: 919109214f22
Revises: 7cf0836793e7
Create Date: 2025-04-28 12:00:12.252891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919109214f22'
down_revision = '7cf0836793e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duree_heures', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrat', schema=None) as batch_op:
        batch_op.drop_column('duree_heures')

    # ### end Alembic commands ###
