"""Passage à debut_fin

Revision ID: cc024e52500f
Revises: c986f13debb4
Create Date: 2025-04-28 10:47:41.136048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc024e52500f'
down_revision = 'c986f13debb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=False),
    sa.Column('prix_horaire', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrat')
    # ### end Alembic commands ###
