"""Ajout contrat_id dans Client

Revision ID: d04073e3bf0b
Revises: fa7f5f603e61
Create Date: 2025-04-28 16:21:17.809804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04073e3bf0b'
down_revision = 'fa7f5f603e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('materiel_fournis', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('materiel_fournis')
        batch_op.drop_column('observation')

    # ### end Alembic commands ###
