"""Ajout du champ demandeur

Revision ID: d935af1245c9
Revises: 856ba7b24132
Create Date: 2025-04-24 08:23:20.619980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd935af1245c9'
down_revision = '856ba7b24132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demandeur', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('demandeur')

    # ### end Alembic commands ###
