"""Passage à debut_fin

Revision ID: e166a434015f
Revises: 3b1bf0566a0f
Create Date: 2025-04-25 09:38:21.711577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e166a434015f'
down_revision = '3b1bf0566a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupe_assignation', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('groupe_assignation')

    # ### end Alembic commands ###
