"""Passage à debut_fin

Revision ID: e5a0c5ac987b
Revises: aa9809148429
Create Date: 2025-04-25 08:37:25.342992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a0c5ac987b'
down_revision = 'aa9809148429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_debut', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_fin', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('date_fin')
        batch_op.drop_column('date_debut')

    # ### end Alembic commands ###
