"""Ajout colonne soldes_annee

Revision ID: ef2ab8a6cd87
Revises: 059f15535207
Create Date: 2025-04-24 15:26:44.300956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ef2ab8a6cd87'
down_revision = '059f15535207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde_annuel', sqlite.JSON(), nullable=True))
        batch_op.drop_column('solde_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde_minutes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('solde_annuel')

    # ### end Alembic commands ###
