"""Ajout contrat_id dans Client

Revision ID: fa7f5f603e61
Revises: 919109214f22
Create Date: 2025-04-28 14:23:18.597052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7f5f603e61'
down_revision = '919109214f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_client_contrat_id', 'contrat', ['contrat_id'], ['id'])

    with op.batch_alter_table('contrat', schema=None) as batch_op:
        batch_op.drop_column('duree_heures')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duree_heures', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_contrat_id', type_='foreignkey')

    # ### end Alembic commands ###
