"""Ajout contrat_id dans Client

Revision ID: fb8fd15e0fbd
Revises: d04073e3bf0b
Create Date: 2025-04-28 16:50:50.428472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8fd15e0fbd'
down_revision = 'd04073e3bf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materiel_fourni', sa.Boolean(), nullable=True))
        batch_op.drop_column('materiel_fournis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materiel_fournis', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('materiel_fourni')

    # ### end Alembic commands ###
